### ISSUE TITLE
Bug: simple-web-notification is not version pinned

### ISSUE THREAD

**Issue by dannyOhNo** [sagiegurari/angular-web-notification#32]
**Describe the bug**
simple-web-notification (https://github.com/sagiegurari/simple-web-notification) released version 2.0.0 yesterday. This build contains breaking changes against some part of our build pipeline (still investigating, but reverting to the previous version 1.0.32 resolves our issues).

**To Reproduce**
Unknown at this time. Will update if I am able to pinpoint.

**Error Stack**
```console
...
[19:43:41] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name (tagCounter)
File: /opt/questis/bower_components/vendor.min.js
...
```

Recommended change is to pin `simple-web-notification` to a version (not the latest).

**Comment by sagiegurari** [comment]
so, ya i have breaking changes. that's why its a major version upgrade.
not sure version pinning is the solution here as i see you are using bower.
i think the real issue is that i dropped bower support as it is dead for at least 3 years.
need to move to npm/yarn/webpack.
I'll remove the bower example from the readme, but i don't want to keep using bower anymore.

**Comment by sagiegurari** [comment]
thinking about it more... i could just add the bower.json back, but not use it myself.
this would unbreak you and won't really impact anything in the library itself....
give me few minutes...

**Comment by sagiegurari** [comment]
version 2.0.1 release. it should resolve your issues, but in general you should move away from bower.
please tell me if its resolve.

**Comment by sagiegurari** [comment]
think this should be resolved.
got no feedback.
closing.
